version: '3'

services:
  nginx:
    build: docker/nginx
    depends_on:
      - php
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html

  php:
    # build: docker/web
    image: rscafi/mongodb-workshop-base-php
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mvertes/alpine-mongo
    volumes:
      - db:/data/db

volumes:
  db:
    driver: local
